export default function Footer() {
  return (
    <footer className="mt-8 text-center text-gray-500 text-sm">
      <p>
        © {new Date().getFullYear()} NYC LEGEND | Created with React, TypeScript
        & Llama AI
      </p>
      <p className="mt-1">
        All SVG compass visualizations are dynamically generated by Llama AI
      </p>
    </footer>
  );
}
